### ISSUE TITLE
v26.3.417 - Incompatibility with JAOPCA

### ISSUE THREAD

**Issue by ubergeek77** [mcenderdragon/Futurepack-API#503]
Edit: Updated title since mcenderdragon pointed out what the real issue is

After updating from Futurepack v26.3.309 to v26.3.417, my server crashes on load. The exception seems to be caused by Futurepack, but thrown by [WrapUp](https://minecraft.curseforge.com/projects/wrapup). I cannot stop using WrapUp as it is required by [JAOPCA](https://minecraft.curseforge.com/projects/jaopca).

The first few lines of the error being thrown is:

`Description: Exception in server tick loop`

`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WrapUp (wrapup)`

`Caused by: java.lang.NoSuchMethodError: futurepack.common.crafting.FPZentrifugeManager.addZentrifugeRecipe(Lnet/minecraft/item/ItemStack;[Lnet/minecraft/item/ItemStack;I)Lfuturepack/common/crafting/ZentrifugeRecipe;`

This does _**not**_ happen on Futurepack v26.3.309.

The full crash log can be found here:

https://pastebin.com/raw/LSnkbAx5

**Comment by mcenderdragon** [comment]
Jopca did use non APi methods, and they have changed in 417. Please report and link this issue on their bug tracker: https://github.com/TheLMiffy1111/JAOPCA/issues.

**Comment by mcenderdragon** [comment]
Valid methods are:
```
public static ZentrifugeRecipe addRecipe(ItemPredicates in, ItemStack[] out, int support)
{
	return instance.addZentrifugeRecipe(in, out, support);
}

public static ZentrifugeRecipe addRecipe(ItemStack in, ItemStack[] out, int support)
{
	return instance.addZentrifugeRecipe(new ItemStackPredicate(in), out, support);
}

public ZentrifugeRecipe addZentrifugeRecipe(ItemPredicates in, ItemStack[] out, int support)
{
	ZentrifugeRecipe z = new ZentrifugeRecipe(in, out, support);
	recipes.add(z);
	FPLog.logger.debug(z.toString());
	return z;
}

```

**Comment by mcenderdragon** [comment]
@TheLMiffy1111 I will poke you since I changed the methods. Also very cool you are supporting the Futurepack :)

**Comment by ubergeek77** [comment]
Thanks! I'll go ahead and file an issue over there.

**Comment by ubergeek77** [comment]
Looks like JAOPCA just resolved this on their end!
